services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  op-succinct:
    build:
      context: .
      dockerfile: ./validity/Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://op-succinct@postgres:5432/op-succinct
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ../data:/data

  proof-conversion-service:
    build:
      context: .
      dockerfile: ./proof-conversion/Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://op-succinct@postgres:5432/op-succinct
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - op-succinct
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../data:/data

volumes:
  postgres-data:
